/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.zz.refresh;

import org.openide.util.NbPreferences;

final class AutoRefreshPanel extends javax.swing.JPanel {

    private final AutoRefreshOptionsPanelController controller;

    AutoRefreshPanel(AutoRefreshOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshOnSave = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(refreshOnSave, org.openide.util.NbBundle.getMessage(AutoRefreshPanel.class, "AutoRefreshPanel.refreshOnSave.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(refreshOnSave)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(refreshOnSave)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(AutoRefreshPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(AutoRefreshPanel.class).getBoolean("someFlag", false));
        // or:eb
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        refreshOnSave.setSelected(NbPreferences.forModule(AutoRefreshPanel.class).getBoolean("refreshOnSave", true));
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(AutoRefreshPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(AutoRefreshPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        NbPreferences.forModule(AutoRefreshPanel.class).putBoolean("refreshOnSave", refreshOnSave.isSelected());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox refreshOnSave;
    // End of variables declaration//GEN-END:variables
}
